### PR TITLE
optimizations / defaults

### PR DESCRIPTION
**Pull request by ag0n-e**
fix webcomponent config

### CODE REVIEW

**Comment by mrabans** [comment]
@dulvui @rcavaliere

**Comment by dulvui** [comment]
@mrabans @ag0n-e Sorry didn't merge it because it is still marked as draft. Should I merge it?

**Comment by ag0n-e** [comment]
@dulvui the answer was yes, no, yes, no, yes :)

I pushed another fix for a breaking change regarding inline images. Now the request should be fine.

**Comment by dulvui** [comment]
@ag0n-e Okay I understand ;-) I merged now

**Pull request merged**
