### PR TITLE
future dst format support for arrivals/departures

### PR DESCRIPTION
**Pull request by ag0n-e**
Arrivals and departures are displayed in the configured time zone. This also applies to flights whose arrival/departure time is outside the currently valid DST. These times are misleading for the viewer, so displayed times can now be corrected according to their own DST.

### CODE REVIEW

**Comment by mrabans** [comment]
@dulvui can you please merge this bugfix?
@sseppi fyi

**Comment by dulvui** [comment]
@mrabans merged now and available on testing
https://webcomponents.opendatahub.testingmachine.eu/webcomponent/flightmap
Let me know if its working correctly, then I'll deploy to production

**Comment by mrabans** [comment]
@dulvui all correct, you can deploy it to prod

**Comment by dulvui** [comment]
@mrabans done

**Pull request merged**
