### PR TITLE
new destination mappings / labels and positions

### PR DESCRIPTION
**Pull request by ag0n-e**
new destinations: position & label map.

### CODE REVIEW

**Comment by mrabans** [comment]
Pipeline is failing due to a problem on the cache service as it seems. Could someone have a look? @rcavaliere @Piiit

**Comment by Piiit** [comment]
> Pipeline is failing due to a problem on the cache service as it seems. Could someone have a look? @rcavaliere @Piiit

Hi @mrabans , yes we are aware of this problem, but it is not in our hands, we need to wait for Github to solve the issue or disable the caches. Lets wait for some hours and see... Cache servers of Github seem down, we have this issue with pip, npm and maven caches at the moment. Not tested others...

**Comment by dulvui** [comment]
The GithubAction cache seems now working again.
Now there's a problem with the reuse check action, because the latest reuse version checks also the npm_modules/ folder created after npm build. I fixed it already on main branch so I'll merge the PR now and it should work.

**Comment by dulvui** [comment]
Everything worked and is now online in the testing webcomponent store:
https://webcomponents.opendatahub.testingmachine.eu/webcomponent/7da57747-0fab-4e2c-89c4-f662d242f920

**Pull request merged**
